/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PredictionMarket__factory } from "./PredictionMarket__factory";
export { Vault__factory } from "./Vault__factory";
