[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
darkbet_prediction_market = "11111111111111111111111111111111"

[programs.devnet]
darkbet_prediction_market = "11111111111111111111111111111111"

[programs.mainnet]
darkbet_prediction_market = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000


